name: psxmpc
description: A new PSX Multipurpose Classified application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html

version: 1.3.3+12
publish_to: none

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  platform: ^3.1.5
  shared_preferences: ^2.2.3
  http:
  provider: ^6.1.2
  connectivity_plus: ^6.0.3
  cached_network_image: ^3.3.1
  theme_manager: ^2.0.4
  flutter_map:
  image_picker: ^1.1.2
  latlong2: ^0.9.1
  sembast: ^3.7.1+2
  path_provider: ^2.1.3
  intl: ^0.19.0
  shimmer: ^3.0.0
  url_launcher: ^6.3.0
  carousel_slider: ^5.0.0
  firebase_core: ^3.2.0
  firebase_core_platform_interface: ^5.1.0
  firebase_messaging: ^15.0.3
  firebase_database: ^11.0.3
  firebase_auth: ^5.1.2
  google_mobile_ads: ^5.1.0
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^6.0.4
  photo_view: ^0.15.0
  progress_dialog_null_safe: ^3.0.0
  flutter_braintree: ^4.0.0
  launch_review: ^3.0.1
  package_info_plus: ^8.0.0
  flutter_credit_card: ^4.0.1
  fluttertoast: ^8.2.6
  permission_handler: ^11.3.1
  permission_handler_platform_interface: ^4.2.1
  geocode: ^1.0.3
  geolocator: ^12.0.0
  flutter_html: ^3.0.0-beta.2
  share_plus: ^9.0.0
  the_apple_sign_in: ^1.1.1
  razorpay_flutter: ^1.3.7
  flutter_native_image: ^0.0.6+1
  flutter_paystack: ^1.0.7
  firebase_dynamic_links: ^6.0.3
  in_app_purchase: ^3.2.0
  flutter_linkify: ^6.0.0
  google_maps_flutter: ^2.7.0
  flutter_datetime_picker_plus: ^2.2.0
  video_thumbnail: ^0.5.3
  video_player: ^2.9.1
  file_picker: ^8.0.6
  geocoding: ^3.0.0
  camera: ^0.11.0+1
  app_tracking_transparency: ^2.0.5
  firebase_crashlytics: ^4.0.3
  map_launcher: ^3.3.1
  device_info_plus: ^10.1.0
  platform_device_id: ^1.0.1
  encrypt: ^5.0.3
  dotted_border: ^2.1.0
  flutter_stripe: ^10.2.0
  flutter_svg:
  firebase_app_check: ^0.3.0+3
  calendar_date_picker2: ^1.1.5
  remixicon: ^1.2.0
  quiver: ^3.2.1
  email_validator: ^3.0.0
  badges: ^3.1.2
  win32: ^5.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
dependency_overrides:
  intl: ^0.17.0-nullsafety.2
  flutter_paystack:
    git:
      url: https://github.com/SawNoiKaungHtetKyaw/flutter_paystack
      ref: master

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/lang/
    - assets/images/placeholder_circle_image.png
    - assets/images/placeholder_image.png
    - assets/images/flutter_buy_and_sell_logo.png
    - assets/images/rec_logo.png
    - assets/images/default_image.png
    - assets/images/user_default_photo.png
    - assets/images/location_onboard.svg
    - assets/images/slider_1.svg
    - assets/images/slider_2.svg
    - assets/images/slider_3.svg
    - assets/images/no_notification.svg
    - assets/images/buy_package.svg
    - assets/images/onboard_language.svg
    - assets/images/chat_list_empty_photo.svg
    - assets/images/demo_alert.png
    - assets/images/google_logo.png
    - assets/images/buy_package_background.png
    - assets/images/item_list_empty.svg
    - assets/images/facebook.svg
    - assets/images/google.svg
    - assets/images/instagram.svg
    - assets/images/pinterest.svg
    - assets/images/twitter.svg
    - assets/images/youtube.svg
    - assets/images/home_bottom.svg
    - assets/images/home_bottom_selected.svg
    - assets/images/payment/
    - assets/images/fa-solid_laptop-house.svg
    - assets/images/storefont.png
    - assets/images/become_a_vendor.png
    - assets/images/profile_vendor_shop.png
    - assets/images/vendor_registeration_success.png
    - assets/images/order_success.svg
    - assets/images/checkout_no_order.png
    - assets/images/empty_cart.svg
    - assets/images/package_2.svg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: ps_standard_font
      fonts:
        - asset: assets/fonts/Product-Sans-Regular.ttf
        - asset: assets/fonts/Product-Sans-Bold-Italic.ttf
        - asset: assets/fonts/Product-Sans-Bold.ttf
        - asset: assets/fonts/Product-Sans-Italic.ttf

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
